name: Build Test Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: 13-3.4/alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/jobrad-gmbh/postgis:13-3.4-alpine
